### ISSUE TITLE
Error Failed to import the app LABINS!

### ISSUE THREAD

**Issue by mcore000** [KPCOFGS/ArcGIS_ExperienceBuilder_LABINS_Map#2]
When I try and import LABINS.zip into ExB Desktop Developer v1.13 on a Windows 11 machine, I get the error message: "Failed to import the app LABINS!" Furthermore, the file size for LABINS.zip is only 1 kb, and when I try to open the file in the Windows File Explorer, then, I get the warning message that Windows cannot open the folder because the compressed zipped folder is invalid.

**Comment by KPCOFGS** [comment]
Hi Mike! I have changed the installation instruction, you either need to download the .zip file from the Release section or use `git clone`

**Comment by shodge17** [comment]
You have to first click on the labins.zip name and it takes you to a second page.  download it from the there  104 MB


Stephen W. Hodge
ISPA / FREAC Director
850-644-2882(w)
850-597-1139(c)
***@***.******@***.***>
________________________________
From: mcore000 ***@***.***>
Sent: Thursday, April 18, 2024 11:18 AM
To: KPCOFGS/ArcGIS_ExperienceBuilder_LABINS_Map ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KPCOFGS/ArcGIS_ExperienceBuilder_LABINS_Map] Error Failed to import the app LABINS! (Issue #2)


When I try and import LABINS.zip into ExB Desktop Developer v1.13 on a Windows 11 machine, I get the error message: "Failed to import the app LABINS!" Furthermore, the file size for LABINS.zip is only 1 kb, and when I try to open the file in the Windows File Explorer, then, I get the warning message that Windows cannot open the folder because the compressed zipped folder is invalid.

**Comment by shodge17** [comment]
Note also, you need to go to Phillip's widget repository and get his 3 custom widgets as well


Stephen W. Hodge
ISPA / FREAC Director
850-644-2882(w)
850-597-1139(c)
***@***.******@***.***>
________________________________

**Comment by mcore000** [comment]
This is odd behavior. I am using the green code button to download the ZIP of the entire repo. This should be the same as cloning the repo. Maybe there is some delay in GitHub. Also, I will grab the custom widgets. Thanks.
